# Generated by Django 4.2.1 on 2023-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdeposit',
            name='income',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditdeposit',
            name='profit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditdeposit',
            name='years',
            field=models.IntegerField(default=1),
        ),
    ]
