# Generated by Django 4.2.1 on 2023-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_creditdeposit_income_creditdeposit_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdeposit',
            name='percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
